### ISSUE TITLE
Onderzoek kwetsbare doelgroep toevoegen

### ISSUE THREAD

**Issue by JikkedH** [nl-design-system/gebruikersonderzoeken#133]
[Spreken met kwetsbaren(1).md](https://github.com/nl-design-system/gebruikersonderzoeken/files/14296419/Spreken.met.kwetsbaren.1.md)

**Comment by JeroenduC** [comment]
Onderzoek toegevoegd: https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/corona/valsplat-corona-kwetsbaren
