### ISSUE TITLE
Onderzoek Afschalen Corona Maatregelen toevoegen

### ISSUE THREAD

**Issue by JikkedH** [nl-design-system/gebruikersonderzoeken#135]
[Straatonderzoek over het afschalen van corona maatregelen (1).md](https://github.com/nl-design-system/gebruikersonderzoeken/files/14296437/Straatonderzoek.over.het.afschalen.van.corona.maatregelen.1.md)

**Comment by JeroenduC** [comment]
Onderzoek toegevoegd: https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/corona/valsplat-corona-straatonderzoek-afschalen-maatregelen
