### ISSUE TITLE
Onderzoek Mijn Aanvragen toevoegen

### ISSUE THREAD

**Issue by MariekeBrouwer** [nl-design-system/gebruikersonderzoeken#184]
[OIP onderzoek Mijn Aanvragen 2023.docx](https://github.com/nl-design-system/gebruikersonderzoeken/files/15331426/OIP.onderzoek.Mijn.Aanvragen.2023.docx)

Het duurde even, omdat we even wilden uitzoeken wat voor ons een handige manier was om het bestand te uploaden en ik wachtte nog van feedback van betrokken collega's en wilde graag jullie format invullen/gebruiken. Dus eindelijk, maar toch :)

**Comment by JeroenduC** [comment]
<img width="353" alt="image" src="https://github.com/nl-design-system/gebruikersonderzoeken/assets/49227194/88082c91-a0aa-44cd-82b8-659b4e5f7667">

**Comment by JeroenduC** [comment]
![image](https://github.com/nl-design-system/gebruikersonderzoeken/assets/49227194/37c13b43-6e0f-4bdd-9ba5-3c7556fe7729)

**Comment by JeroenduC** [comment]
Pull request voor onderzoek is aangemaakt, nog even wachten op de review en dan kan hij live.

Wel nog een vraagje, de plaatjes in het Word document worden steeds kleiner. De eerste is nog wel okay, maar daarna is de inhoud niet meer zo goed zichtbaar. Zijn er grotere screenshots die we zouden kunnen gebruiken?

**Comment by MariekeBrouwer** [comment]
![MijnAanvragen_Lopende_DesktopMijnAanvragen](https://github.com/nl-design-system/gebruikersonderzoeken/assets/149144374/44bee2ae-02e8-43f9-9c9b-9de8d6d8f531)
![Aanvraag List - variant 03 - Desktoprefinement](https://github.com/nl-design-system/gebruikersonderzoeken/assets/149144374/fd0e0570-c9b9-46f5-9529-f8664055e657)
![LopendeAanvragen_Desktopdocument uploaden](https://github.com/nl-design-system/gebruikersonderzoeken/assets/149144374/98143f0f-234d-4aa0-808a-cde235689fa0)
![Final variant - Desktopdesktop_afbeelding](https://github.com/nl-design-system/gebruikersonderzoeken/assets/149144374/a991e1e1-3227-4c26-b51d-c3f0c1a60287)

**Comment by JeroenduC** [comment]
Testje

![image](https://github.com/nl-design-system/gebruikersonderzoeken/assets/49227194/6d9a97e6-e03a-41f8-8150-c815d125cbd3)

**Comment by JeroenduC** [comment]
Plaatjes gefixt! Onderzoek staat online: https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/mijn-zaken/groningen-mijn-omgeving
