### ISSUE TITLE
Zoeken implementeren

### ISSUE THREAD

**Issue by JeroenduC** [nl-design-system/gebruikersonderzoeken#35]
Het zou handig zijn om te kunnen zoeken met een zoekfunctie door het gebruikersonderzoek.

**Comment by JeroenduC** [comment]
Aanvragen bij: https://docsearch.algolia.com/

Github pagina meegeven.

**Comment by JeroenduC** [comment]
Aanvraag gedaan. Wachten op respons.

**Comment by JeroenduC** [comment]
Toegelaten! Ik heb een account gemaakt en heb mijzelf toegevoegd bij het project.

Onderstaande heb ik in de mail gekregen. @Yolijn : Moet ik nog iets doen?

**CSS**
Copy this snippet at the end of the HTML <head> tag
<link rel="stylesheet" href="[https://cdn.jsdelivr.net/npm/@docsearch/css@3"/></pre></li>](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fcdn.jsdelivr.net.mcas.ms%2Fnpm%2F%40docsearch%2Fcss%403%22%2F%3E%3C%2Fpre%3E%3C%2Fli%3E%3FMcasTsid%3D20893&McasCSRF=aba37725c1b7499069b4c160c4ba7bc6f7fdbfe5b1edd0f65c78b254d7e489c6)

**JavaScript**
Copy this snippet at the end of the HTML <body> tag
<script src="[https://cdn.jsdelivr.net/npm/@docsearch/js@3"></script>](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fcdn.jsdelivr.net.mcas.ms%2Fnpm%2F%40docsearch%2Fjs%403%22%3E%3C%2Fscript%3E%3FMcasTsid%3D20893&McasCSRF=aba37725c1b7499069b4c160c4ba7bc6f7fdbfe5b1edd0f65c78b254d7e489c6)
<script type="text/javascript">
docsearch({
appId: HWYTAR8XU5,
apiKey: 68720c7d6f2fe2fb3e01710c41e9b596,
indexName: gebruikersonderzoek,
container: '### REPLACE ME WITH A CONTAINER (e.g. div) ###'
debug: false // Set debug to true if you want to inspect the modal
});
</script>

**Comment by Yolijn** [comment]
Nice! Ik denk dat ik hiermee aan de slag kan, laat het je weten! 👍
